# Generated by Django 6.0.4 on 2026-04-08 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_source_url_alter_productimage_image'),
        ('recommendations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'View'), ('cart', 'Add to cart'), ('purchase', 'Purchase')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'kind', '-created_at'], name='recommendat_user_id_7fcbcd_idx'), models.Index(fields=['product', 'kind', '-created_at'], name='recommendat_product_a1eca5_idx')],
            },
        ),
    ]
