# Generated by Codex on 2026-05-09

from django.db import migrations, models
from django.utils.text import slugify


def populate_skus(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    for product in Product.objects.order_by("id"):
        if product.sku:
            continue
        base = slugify(product.name)[:90] or f"product-{product.id}"
        sku = base
        i = 2
        while Product.objects.filter(sku=sku).exclude(id=product.id).exists():
            suffix = f"-{i}"
            sku = f"{base[:100 - len(suffix)]}{suffix}"
            i += 1
        product.sku = sku
        product.save(update_fields=["sku"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productimage_source_url_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.SlugField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.RunPython(populate_skus, migrations.RunPython.noop),
    ]
